# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='package_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
